added env secrets

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,6 +8,9 @@
 #  BOOK_FIREBASE_MEASUREMENT_ID: string;
 #  BOOK_GOOGLE_API_KEY: string;
 
+#  BOOK_SUPABASE_URL: string;
+#  BOOK_SUPABASE_ANON_KEY: string;
+
 # Simple workflow for deploying static content to GitHub Pages
 name: Deploy static content to Pages
 
@@ -47,8 +50,23 @@ jobs:
       BOOK_FIREBASE_APP_ID: ${{ secrets.BOOK_FIREBASE_APP_ID }}
       BOOK_FIREBASE_MEASUREMENT_ID: ${{ secrets.BOOK_FIREBASE_MEASUREMENT_ID }}
       BOOK_GOOGLE_API_KEY: ${{ secrets.BOOK_GOOGLE_API_KEY }}
+      BOOK_SUPABASE_URL: ${{ secrets.BOOK_SUPABASE_URL }}
+      BOOK_SUPABASE_ANON_KEY: ${{ secrets.BOOK_SUPABASE_ANON_KEY }}
       BOOK_CUSTOM_MODE: gh-pages
     steps:
+      - name: Verify All Secrets
+        run: |
+          SECRETS=("BOOK_FIREBASE_API_KEY" "BOOK_FIREBASE_AUTH_DOMAIN" "BOOK_FIREBASE_DATABASE_URL" "BOOK_FIREBASE_PROJECT_ID" "BOOK_FIREBASE_STORAGE_BUCKET" "BOOK_FIREBASE_MESSAGING_SENDER_ID" "BOOK_FIREBASE_APP_ID" "BOOK_FIREBASE_MEASUREMENT_ID" "BOOK_GOOGLE_API_KEY" "BOOK_SUPABASE_URL" "BOOK_SUPABASE_ANON_KEY")
+
+          for SECRET in "${SECRETS[@]}"; do
+            if [[ -z "${{ secrets[SECRET] }}" ]]; then
+              echo "❌ $SECRET is missing"
+              exit 1
+            else
+              echo "✅ $SECRET is set"
+            fi
+          done
+
       - name: Checkout
         uses: actions/checkout@v4
       - name: Set up Node
@@ -59,7 +77,7 @@ jobs:
       - name: Install dependencies
         run: npm ci --legacy-peer-deps
       - name: Build
-        run: npm run build
+        run: NODE_ENV=production npm run build
       - name: Setup Pages
         uses: actions/configure-pages@v4
       - name: Upload artifact
